"""Add deployed_url to Project model

Revision ID: 9bc539da0404
Revises: c67471d19c76
Create Date: 2024-12-11 22:08:50.489567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc539da0404'
down_revision = 'c67471d19c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployed_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('deployed_url')

    # ### end Alembic commands ###
