"""Add social media links to User model

Revision ID: c67471d19c76
Revises: c9b039b9a2c6
Create Date: 2024-12-11 20:46:09.669809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67471d19c76'
down_revision = 'c9b039b9a2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('github')
        batch_op.drop_column('youtube')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('twitter')

    # ### end Alembic commands ###
